Spoonacular integration recipe update
ECE444-2020Fall/project1-plateup-group5-pyromaniacs pull request #41
Opened 2020-10-18 19:59 UTC by UTkzhang

added recipe retrieval, recipe update, instructions, and fixed some bugs

sample recipe GET (random, limit 20)
![image](https://user-images.githubusercontent.com/34317307/96378631-62aaf800-115b-11eb-9e82-c029b6712edc.png)

2020-10-18 22:13 UTC, shadow-blade-X requested changes
Commented, please update

2020-10-18 22:13 UTC, shadow-blade-X commented on PlateUp-flask/models.py
> +    step = db.Column(db.String)
Can you change the name "step" to a better name so I know what it will contain?

2020-10-18 22:13 UTC, shadow-blade-X commented on PlateUp-flask/run.py
> +                        new_recipe_tags = new_recipe_tags.strip(", ")
Can you try to group the modification on new_recipe_tags together to a function? It looks a bit messy right now.

2020-10-18 22:13 UTC, shadow-blade-X commented on PlateUp-flask/run.py
> +                                new_instruction_ingredients, new_instruction_equipment)
Same here, group the generation of new_instruction to a function. Call it instead of leave things here.

2020-10-18 22:13 UTC, shadow-blade-X commented on PlateUp-flask/run.py
> +                                        new_recipe_preview_media_url, new_recipe_tags)
Group the generation of new_recipe to a single function like transfer_recipe_format or something like that. It looks a bit messy here.

2020-10-19 00:45 UTC, UTkzhang commented on PlateUp-flask/models.py
> +    step = db.Column(db.String)
sure

2020-10-19 00:45 UTC, UTkzhang commented on PlateUp-flask/run.py
> +                        new_recipe_tags = new_recipe_tags.strip(", ")
sure

2020-10-19 00:47 UTC, UTkzhang commented on PlateUp-flask/run.py
> +                                new_instruction_ingredients, new_instruction_equipment)
sure

2020-10-19 02:17 UTC, shadow-blade-X approved these changes

2020-10-19 02:19 UTC, merged