Recipe Step-By-Step Instructions
ECE444-2020Fall/project1-plateup-group5-pyromaniacs pull request #78
Opened 2020-11-03 20:22 UTC by fcpranav

This PR completes the "Step-By-Step Instructions" feature. This feature was developed with mock data. The backend functionality is not yet available. A later ticket might be needed for clearing up any integration issues.

Link for the progress button component used: https://github.com/xinghui0000/react-native-progress-button

Here are some screenshots:

![image](https://user-images.githubusercontent.com/42985270/98072245-96607000-1e33-11eb-8476-8f8b86727a33.png)
![image](https://user-images.githubusercontent.com/42985270/98072271-a4ae8c00-1e33-11eb-8fd0-01a6426f58e0.png)

Time Spent: 8 hours

2020-11-03 20:27 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +          duration: (steps[0].time ? steps[0].time * 1000 : 3000)
Duration is in ms, we assume the timer data will be provided in seconds.

2020-11-04 02:56 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +          duration: (steps[0].time ? steps[0].time * 1000 : 3000)
I think 3s is probably too short if we don't know the data. I'd say 10s is probably more realistic

2020-11-04 02:56 UTC, eanile commented
I noticed that the pause button is the same width as the card. I think we should be consistent in that the recipe details screen has it not as wide as the card.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/mock-http.js
>          ],
You think it's fine to not have a step where there are ingredients but no equipment?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/navigation/Screens.js
> +              iconColor={argonTheme.COLORS.SECONDARY}
Still not sure about this as the title colour. In other pages with white headers, the default (~black) is used.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeDetails.js
> +          <Button style={styles.button} onPress={() => this.props.navigation.navigate('RecipeStepByStep', { id: this.props.route.params.id })}>
Line is pretty long, can we split this up

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeDetails.js
> +          {loading
The auto formatter did this?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    this.handleProgressAnimatedFinished = this.handleProgressAnimatedFinished.bind(this);
Please make all these functions look like

`startStepTimer = () => {...}`

instead of

`startStepTimer() {...}`

so that you can get rid of all these bind statements.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +          duration: stepDetails.time ? stepDetails.time * 1000 : 3000
Can we make this 3000 (or 10000 as I suggested previously) a constant in this file?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        progress: 100,
Why do we set progress to 100 when starting the timer?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_instruction: instructions } } } = this.props;
In the constructor you use steps, here you use instructions. We should be consistent.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        cookingComplete: false,
Is it necessary to set this here?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        stepDetails: instructions[currentStep + 1 - 1], // Array index starts at 0
Why do we need to do + 1 - 1 here? Can't we just eliminate that? Or you just want to make it clear current step is being incremented? If so, we may want to define a const in this if statement for `nextStep = currentStep + 1` just so it's clear, up to you.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        buttonState: 'progress',
What is this for? In other places you set it to static. However, in pauseStepTimer you don't. Kind of confused as to the purpose. You may want to add a comment in the constructor for potentially unintuitive fields in the state (or at least fields that require me to look at the entire file to understand what they do: I don't want to do that).

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_instruction: instructions } } } = this.props;
Same here, use steps or instructions but not both.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        stepDetails: instructions[currentStep - 1 - 1], // Array index starts at 0
Same here with the currentStep - 1, may want to make a variable for it

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +            style={{ width: '100%', height: '100%' }}
Will this mean that huge images will take up the whole screen? You should test with a very large image to see what happens. We may want to limit the size to specific dimensions.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_preview: recipe } } } = this.props;
Can you also change the RecipeDetails component where I grabbed the recipe/ingredients/instructions to match this style? Didn't know you could do this.

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +            <TouchableOpacity style={styles.stepNavigation} onPress={this.decrementStep}>
Is there a reason why these both have the same style?

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +            <TouchableOpacity style={styles.stepNavigation} onPress={this.incrementStep}>
Same here, has the same style that its parent has

2020-11-04 03:21 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +const mapDispatchToProps = { getRecipeDetails };
This is never used.

2020-11-04 03:54 UTC, fcpranav commented on PlateUp-reactnative/mock-http.js
>          ],
This is just mock data. An example of equipment but no ingredients is what if the step is to put the item into the fridge. Technically no ingredients for the step.

2020-11-04 03:54 UTC, fcpranav commented on PlateUp-reactnative/navigation/Screens.js
> +              iconColor={argonTheme.COLORS.SECONDARY}
This matches the Figma, we can leave the decision to Kevin.

2020-11-04 03:55 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeDetails.js
> +          {loading
Yup

2020-11-04 03:56 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +            style={{ width: '100%', height: '100%' }}
It takes the size of the container. The parent container is fixed in size, so technically no.

2020-11-04 03:59 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +const mapDispatchToProps = { getRecipeDetails };
I'll remove it 👍 , copy paste mistake.

2020-11-04 03:59 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    this.handleProgressAnimatedFinished = this.handleProgressAnimatedFinished.bind(this);
Sure, but for what its worth, both methods are equally valid. I'd even say that this method is more explicit in exactly what's happening.

2020-11-04 04:38 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    this.handleProgressAnimatedFinished = this.handleProgressAnimatedFinished.bind(this);
I don't think its necessary. We kind of already know that since the function is in the component, it belongs to it. Binding it explicitly doesn't really add anything.

2020-11-04 04:54 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeDetails.js
> +          <Button style={styles.button} onPress={() => this.props.navigation.navigate('RecipeStepByStep', { id: this.props.route.params.id })}>
Yeah sure.

2020-11-04 04:54 UTC, fcpranav commented on PlateUp-reactnative/mock-http.js
>          ],
Also I intentionally do this to ensure it properly displays images for cases where there is no images for one array, etc.

2020-11-04 04:55 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +          duration: (steps[0].time ? steps[0].time * 1000 : 3000)
Yep, I'll make this change.

2020-11-04 05:01 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_preview: recipe } } } = this.props;
Sure

2020-11-04 05:05 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +            <TouchableOpacity style={styles.stepNavigation} onPress={this.decrementStep}>
The Block shouldn't have the styling, copy paste error. I'll fix this.

2020-11-04 05:06 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +          duration: stepDetails.time ? stepDetails.time * 1000 : 3000
Yeah, good idea.

2020-11-04 05:07 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        progress: 100,
The component works like this, I believe it is actually the upper bound and it transitions to it. It doesn't explicitly say this in the documentation, but the example they do is similar. One of the reasons why I was having such a hard time getting this to work.

2020-11-04 05:08 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_instruction: instructions } } } = this.props;
Agree.

2020-11-04 05:09 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        stepDetails: instructions[currentStep + 1 - 1], // Array index starts at 0
I'm just making it clear that we are doing +1 to show that we are looking at the next step and -1 for sake of index starting at 0. I'll define a const.

2020-11-04 05:12 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const { recipeDetails: { data: { recipe_instruction: instructions } } } = this.props;
Agree

2020-11-04 05:12 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        stepDetails: instructions[currentStep - 1 - 1], // Array index starts at 0
Addressing

2020-11-04 05:13 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        buttonState: 'progress',
This field relates to the library I am using for the progress bar. Feels weird explaining this in the comments, the docs for the component should just be read. I'll add a note that this is specifically for the progress bar component.

2020-11-04 05:18 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        cookingComplete: false,
Technically no, it is necessary for the decrementStep() function. I think it's fine leaving it here to clearly show the states, however, I'm good to remove it also if you'd like.

2020-11-04 06:02 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        progress: 100,
I'd explain it if it was that complicated/confusing then.

2020-11-04 06:03 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        cookingComplete: false,
For other cases when you change the state, you don't always set the entire state though. We should probably be consistent, though if you don't want to change it it's fine

2020-11-04 06:05 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        buttonState: 'progress',
I mean, if I'm looking through code, I shouldn't have to constantly refer to documentation to understand it. Sometimes I wouldn't know when to refer to it too. Complicated/confusing things should be explained if they can be.

2020-11-04 06:10 UTC, eanile requested changes

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeDetails.js
> +            <Text style={styles.buttonText}>Let&apos;s Go!</Text>
Think something went wrong here with the text.

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeDetails.js
> +    const { data: { recipe_preview: recipe }, error } = recipeDetails;
I think this causes an error. If error is defined, then trying to access data will cause an exception. Please only get the error here and get the data after the error is checked.

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +const defaultStepTime = 10000;
nit: constant name should LOOK_LIKE_THIS

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    // Documentation on it can be found at: https://github.com/xinghui0000/react-native-progress-button
I guess this is fine for now, but we should really be actually discussing here what the confusing fields do instead of just refering to documentation. Especially because we have no comments. Having comments for complicated stuff just makes it easier to read through.

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const nextStep = currentStep + 1;
This could be moved inside the if statement. Pretty minor, but still.

2020-11-04 06:10 UTC, eanile commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    const nextStep = currentStep - 1;
Same here.

2020-11-04 06:13 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeDetails.js
> +            <Text style={styles.buttonText}>Let&apos;s Go!</Text>
Nope, I escape the `'` character. The linter was complaining.

2020-11-04 06:14 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeDetails.js
> +    const { data: { recipe_preview: recipe }, error } = recipeDetails;
Oh nice catch, I totally forgot about this

2020-11-04 06:16 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +const defaultStepTime = 10000;
Agree, I'll make the change

2020-11-04 06:22 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        cookingComplete: false,
Okay sure, I can remove it

2020-11-04 06:28 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +        progress: 100,
You're right, I should note this down as a comment.

2020-11-04 06:30 UTC, fcpranav commented on PlateUp-reactnative/screens/RecipeStepByStep.js
> +    // Documentation on it can be found at: https://github.com/xinghui0000/react-native-progress-button
Sure I'll add some comments.

2020-11-04 06:47 UTC, eanile approved these changes
Only thing is the colour of the header title, but that can easily be changed later

2020-11-04 06:51 UTC, fcpranav commented
Yeah, we can schedule a team QA session where we review the UI w/ Kevin present.

2020-11-04 06:52 UTC, merged