Inventory shopping api
ECE444-2020Fall/project1-plateup-group5-pyromaniacs pull request #94
Opened 2020-11-07 01:37 UTC by UTkzhang

Added support for basic inventory and shopping apis, as well as ability for user to clear shopping cart and flash to ingredients.

Also added recipe inventory checker. If user has enough ingredients for recipe, it deducts and returns "Inventory updated, enough ingredients to proceed", if the user doesn't, it adds the missing ingredients to the shopping list and returns "Not enough ingredients, added to shopping list".

2020-11-07 03:14 UTC, UTkzhang commented
#28 #29 #30

2020-11-07 03:34 UTC, shadow-blade-X requested changes

2020-11-07 03:34 UTC, shadow-blade-X commented on PlateUp-flask/run.py
> +    app.run(host='0.0.0.0', debug=True)
Please set debug to False here

2020-11-07 03:34 UTC, shadow-blade-X commented on PlateUp-flask/run.py
> +                    return Response("Bad unit match while flashing to inventory.")
There should be a status code to represent error here

2020-11-09 00:00 UTC, UTkzhang commented on PlateUp-flask/run.py
> +                    return Response("Bad unit match while flashing to inventory.")
fixed

2020-11-09 00:00 UTC, UTkzhang commented on PlateUp-flask/run.py
> +    app.run(host='0.0.0.0', debug=True)
fixed

2020-11-09 00:06 UTC, shadow-blade-X approved these changes

2020-11-09 00:32 UTC, merged